[2023-11-23T21:04:16.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T22:30:11.481856+00:00 [queued]>
[2023-11-23T21:04:16.272+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T22:30:11.481856+00:00 [queued]>
[2023-11-23T21:04:16.272+0000] {taskinstance.py:1361} INFO - Starting attempt 10 of 10
[2023-11-23T21:04:16.281+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Data_transform_and_load> on 2023-11-22 22:30:11.481856+00:00
[2023-11-23T21:04:16.285+0000] {standard_task_runner.py:57} INFO - Started process 1136 to run task
[2023-11-23T21:04:16.287+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'COVID-19', 'Data_transform_and_load', 'manual__2023-11-22T22:30:11.481856+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmppwjmm5uj']
[2023-11-23T21:04:16.289+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask Data_transform_and_load
[2023-11-23T21:04:16.318+0000] {task_command.py:416} INFO - Running <TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T22:30:11.481856+00:00 [running]> on host 89d301135b3a
[2023-11-23T21:04:16.498+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='COVID-19' AIRFLOW_CTX_TASK_ID='Data_transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T22:30:11.481856+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T22:30:11.481856+00:00'
[2023-11-23T21:04:16.749+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl.py", line 52, in data_transform_and_load
    df_departements_region['num_departement'] = df_departements_region['num_departement'].astype(int)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 138, in _astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: invalid literal for int() with base 10: '2A'
[2023-11-23T21:04:16.761+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=COVID-19, task_id=Data_transform_and_load, execution_date=20231122T223011, start_date=20231123T210416, end_date=20231123T210416
[2023-11-23T21:04:16.769+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task Data_transform_and_load (invalid literal for int() with base 10: '2A'; 1136)
[2023-11-23T21:04:16.780+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T21:04:16.792+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
