[2023-11-24T15:32:39.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T15:32:39.168+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T15:32:39.169+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-24T15:32:39.193+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Data_transform_and_load> on 2023-11-22 19:29:07.263785+00:00
[2023-11-24T15:32:39.200+0000] {standard_task_runner.py:57} INFO - Started process 100 to run task
[2023-11-24T15:32:39.205+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'COVID-19', 'Data_transform_and_load', 'manual__2023-11-22T19:29:07.263785+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmphmabqwz5']
[2023-11-24T15:32:39.211+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask Data_transform_and_load
[2023-11-24T15:32:39.283+0000] {task_command.py:416} INFO - Running <TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [running]> on host 3742b108fdc7
[2023-11-24T15:32:39.603+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='COVID-19' AIRFLOW_CTX_TASK_ID='Data_transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T19:29:07.263785+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T19:29:07.263785+00:00'
[2023-11-24T15:32:40.105+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T15:32:40.560+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona'] = df_passage['nbre_pass_corona'].fillna(0).astype(int)

[2023-11-24T15:32:40.608+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:74: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot'] = df_passage['nbre_pass_tot'].fillna(0).astype(int)

[2023-11-24T15:32:40.635+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona_h'] = df_passage['nbre_pass_corona_h'].fillna(0).astype(int)

[2023-11-24T15:32:40.665+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:76: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona_f'] = df_passage['nbre_pass_corona_f'].fillna(0).astype(int)

[2023-11-24T15:32:40.691+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:77: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot_h'] = df_passage['nbre_pass_tot_h'].fillna(0).astype(int)

[2023-11-24T15:32:40.719+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:78: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot_f'] = df_passage['nbre_pass_tot_f'].fillna(0).astype(int)

[2023-11-24T15:32:40.731+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T15:32:40.754+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_etl.py", line 84, in data_transform_and_load
    cursor.execute("INSERT INTO passage (nombre_passage_corona, nombre_passage_total, nombre_passage_corona_h, nombre_passage_corona_f, nombre_passage_total_h, nombre_passage_total_f) VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT (id_passage) DO NOTHING",
psycopg2.ProgrammingError: can't adapt type 'numpy.int64'
[2023-11-24T15:32:40.768+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=COVID-19, task_id=Data_transform_and_load, execution_date=20231122T192907, start_date=20231124T153239, end_date=20231124T153240
[2023-11-24T15:32:40.794+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task Data_transform_and_load (can't adapt type 'numpy.int64'; 100)
[2023-11-24T15:32:40.826+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T15:32:40.856+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
